name: motopro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  dio: ^5.2.0
  cupertino_icons: ^1.0.8
  path: ^1.8.3
  file_selector: ^1.0.0
  provider: ^6.1.1
  file_picker: ^10.2.0
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/user_placeholder.png
    - assets/banner.png
    - assets/icon/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
